import CarDetailsParent from "../../components/CarDetailsParent";
import img1 from '../../assets/new Detail page/Toyota coaster/PICS NEW1_0000_IMG-20240109-WA0053.jpg';
import img2 from '../../assets/new Detail page/Toyota coaster/PICS NEW1_0001_IMG-20240109-WA0061.jpg';
import img3 from '../../assets/new Detail page/Toyota coaster/PICS NEW1_0002_IMG-20240109-WA0057.jpg';
import img4 from '../../assets/new Detail page/Toyota coaster/PICS NEW1_0003_IMG-20240109-WA0063.jpg';

const ToyotaCoaster = () => {
    return (
        <div data-aos="fade-left">
            <CarDetailsParent img1={img1} img2={img2} img3={img3} img4={img4} g1={img1} g2={img2} g3={img3} g4={img4} title={"Luxury Transformed: CMC Automobile Outfits' Bespoke Toyota Coaster Enhancements"} des={"Experience the epitome of luxury travel with CMC Automobile Outfits' specialized modifications tailored for the Toyota Coaster. Elevate this exceptional vehicle to new heights of opulence and sophistication with exclusive upgrades crafted to redefine luxury travel."} li1={"Customized Interior Opulence: Indulge in unparalleled comfort with bespoke interiors featuring premium leather, elegant trims, and personalized designs, transforming the Coaster's cabin into a lavish retreat."} li2={"Advanced Entertainment Systems: Enjoy top-tier entertainment on the go with cutting-edge audio-visual installations, high-definition displays, premium sound systems, and seamless connectivity for a luxurious travel experience."} li3={"Enhanced Comfort and Functionality: Elevate comfort levels with advanced seating arrangements, climate control systems, and refined ergonomics, ensuring an indulgent and convenient journey for passengers."} li4={"Exterior Styling Enhancements: Redefine the Coaster's exterior appeal with exclusive body enhancements, custom paint finishes, and distinctive design elements, making a striking statement wherever it travels."} vTitle={"CMC Automobile Outfits is synonymous with unparalleled craftsmanship"} vDes={"extending their expertise to transform the Toyota Coaster into a pinnacle of luxury travel. These modifications epitomize meticulous attention to detail, seamlessly blending comfort, technology, and sophistication to redefine travel experiences."} bTitle={"Opulent Travel: CMC Automobile Outfits' Signature Toyota Coaster Upgrades"} bDes1={"Embark on a journey of luxury and comfort with CMC Automobile Outfits' signature modifications exclusively tailored for the Toyota Coaster."} bDes2={" Their commitment to superior craftsmanship and innovation ensures that every enhancement encapsulates sophistication, luxury, and individuality, promising an extraordinary travel experience for passengers. Elevate your Toyota Coaster to an unmatched standard of opulence with CMC's exclusive upgrades."}/>
        </div>
    );
};

export default ToyotaCoaster;